services:
  mega_build:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: megacmd-alpine
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
