name: Build Archives for MEGAcmd on Alpine

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

env:
  PREFIX: megacmd_alpine_${{ github.ref_name }}

jobs:
  build-arm64:
    name: Build arm64 archive
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and extract artifact
        run: |
          docker build \
            --platform linux/arm64 \
            --target final \
            -t local/megacmd:arm64 .

          container_id=$(docker create local/megacmd:arm64)
          docker cp "$container_id:/build/${PREFIX}_aarch64.tar.gz" ./${PREFIX}_aarch64.tar.gz
          docker rm "$container_id"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREFIX }}_aarch64
          path: ${{ env.PREFIX }}_aarch64.tar.gz

  build-amd64:
    name: Build x64 archive
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and extract artifact
        run: |
          docker build \
            --platform linux/amd64 \
            --target final \
            -t local/megacmd:amd64 .

          container_id=$(docker create local/megacmd:amd64)
          docker cp "$container_id:/build/${PREFIX}_x86_64.tar.gz" ./${PREFIX}_x86_64.tar.gz
          docker rm "$container_id"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREFIX }}_x86_64
          path: ${{ env.PREFIX }}_x86_64.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [build-arm64, build-amd64]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            artifacts/${{ env.PREFIX }}_aarch64/${{ env.PREFIX }}_aarch64.tar.gz
            artifacts/${{ env.PREFIX }}_x86_64/${{ env.PREFIX }}_x86_64.tar.gz
            